version: '3.1'

services:
  client:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./src:/usr/share/nginx/html
  nextjs:
        ports:
          - 3000:3000
        build:
          context: .
          dockerfile: Dockerfile
    