version: '3.1'

services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
   
  nextjs:
        ports:
          - 3000:3000
        build:
          context: .
          dockerfile: Dockerfile
    